#pragma once

#define _EXPAND(X) X
#define __VA_NARGS_HELPER_0(                        \
_1,  _2,   _3,  _4,  _5,  _6,  _7,  _8,  _9, _10,   \
_11, _12, _13, _14, _15, _16, _17, _18, _19, _20,   \
_21, _22, _23, _24, _25, _26, _27, _28, _29, _30,   \
_31, _32, _33, _34, _35, _36, _37, _38, _39, _40,   \
_41, _42, _43, _44, _45, _46, _47, _48, _49, _50,   \
_51, _52, _53, _54, _55, _56, _57, _58, _59, _60,   \
_61, _62, _63, _64, N, ...) N
#define __VA_NARGS_HELPER_1(...) _EXPAND(__VA_NARGS_HELPER_0(__VA_ARGS__,   \
    63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, \
    47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, \
    31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, \
    15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0))
#define __VA_NARGS_HELPER_2(...) unused, __VA_ARGS__
#define __VA_NARGS__(...) __VA_NARGS_HELPER_1(__VA_NARGS_HELPER_2(__VA_ARGS__))

#define __VA_NARGS_BOOL_HELPER_1(...) _EXPAND(__VA_NARGS_HELPER_0(__VA_ARGS__,   \
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, \
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, \
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, \
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0))
#define __VA_NARGS_BOOL__(...) __VA_NARGS_BOOL_HELPER_1(__VA_NARGS_HELPER_2(__VA_ARGS__))

#define __VA_FOR_EACH(MACRO, ...) _CRT_CONCATENATE(__VA_FOR_EACH_, __VA_NARGS__(__VA_ARGS__)) (MACRO, __VA_ARGS__)

#define __VA_ARG_0(_0, ...) _0
#define __VA_ARG_1(_0, _1, ...) _1
#define __VA_ARG_2(_0, _1, _2, ...) _2
#define __VA_ARG_3(_0, _1, _2, _3, ...) _3
#define __VA_ARG_4(_0, _1, _2, _3, _4, ...) _4
#define __VA_ARG_5(_0, _1, _2, _3, _4, _5, ...) _5
#define __VA_ARG_6(_0, _1, _2, _3, _4, _5, _6, ...) _6
#define __VA_ARG_7(_0, _1, _2, _3, _4, _5, _6, _7, ...) _7
#define __VA_ARG_8(_0, _1, _2, _3, _4, _5, _6, _7, _8, ...) _8
#define __VA_ARG_9(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, ...) _9
#define __VA_ARG_10(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, ...) _10
#define __VA_ARG_11(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, ...) _11
#define __VA_ARG_12(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, ...) _12
#define __VA_ARG_13(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, ...) _13
#define __VA_ARG_14(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, ...) _14
#define __VA_ARG_15(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, ...) _15
#define __VA_ARG_16(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, ...) _16
#define __VA_ARG_17(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, ...) _17
#define __VA_ARG_18(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, ...) _18
#define __VA_ARG_19(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, ...) _19
#define __VA_ARG_20(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, ...) _20
#define __VA_ARG_21(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, ...) _21
#define __VA_ARG_22(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, ...) _22
#define __VA_ARG_23(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, ...) _23
#define __VA_ARG_24(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, ...) _24
#define __VA_ARG_25(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, ...) _25
#define __VA_ARG_26(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, ...) _26
#define __VA_ARG_27(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, ...) _27
#define __VA_ARG_28(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, ...) _28
#define __VA_ARG_29(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, ...) _29
#define __VA_ARG_30(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, ...) _30
#define __VA_ARG_31(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, ...) _31
#define __VA_ARG_32(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, ...) _32
#define __VA_ARG_33(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, ...) _33
#define __VA_ARG_34(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, ...) _34
#define __VA_ARG_35(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, ...) _35
#define __VA_ARG_36(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, ...) _36
#define __VA_ARG_37(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, ...) _37
#define __VA_ARG_38(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, ...) _38
#define __VA_ARG_39(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, ...) _39
#define __VA_ARG_40(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, ...) _40
#define __VA_ARG_41(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, ...) _41
#define __VA_ARG_42(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, ...) _42
#define __VA_ARG_43(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, ...) _43
#define __VA_ARG_44(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, ...) _44
#define __VA_ARG_45(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, ...) _45
#define __VA_ARG_46(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, ...) _46
#define __VA_ARG_47(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, ...) _47
#define __VA_ARG_48(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, ...) _48
#define __VA_ARG_49(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, ...) _49
#define __VA_ARG_50(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, ...) _50
#define __VA_ARG_51(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, ...) _51
#define __VA_ARG_52(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, ...) _52
#define __VA_ARG_53(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, ...) _53
#define __VA_ARG_54(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, ...) _54
#define __VA_ARG_55(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, ...) _55
#define __VA_ARG_56(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, _56, ...) _56
#define __VA_ARG_57(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, _56, _57, ...) _57
#define __VA_ARG_58(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, _56, _57, _58, ...) _58
#define __VA_ARG_59(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, _56, _57, _58, _59, ...) _59
#define __VA_ARG_60(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, _56, _57, _58, _59, _60, ...) _60
#define __VA_ARG_61(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, _56, _57, _58, _59, _60, _61, ...) _61
#define __VA_ARG_62(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, _56, _57, _58, _59, _60, _61, _62, ...) _62
#define __VA_ARG_63(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, _56, _57, _58, _59, _60, _61, _62, _63, ...) _63

#define __VA_FOR_EACH_0(MACRO, ...)

#define __VA_FOR_EACH_1(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))

#define __VA_FOR_EACH_2(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))

#define __VA_FOR_EACH_3(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))

#define __VA_FOR_EACH_4(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))

#define __VA_FOR_EACH_5(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))

#define __VA_FOR_EACH_6(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))

#define __VA_FOR_EACH_7(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))

#define __VA_FOR_EACH_8(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))

#define __VA_FOR_EACH_9(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))

#define __VA_FOR_EACH_10(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))

#define __VA_FOR_EACH_11(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))

#define __VA_FOR_EACH_12(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))

#define __VA_FOR_EACH_13(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))

#define __VA_FOR_EACH_14(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))

#define __VA_FOR_EACH_15(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))

#define __VA_FOR_EACH_16(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))

#define __VA_FOR_EACH_17(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))

#define __VA_FOR_EACH_18(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))

#define __VA_FOR_EACH_19(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))

#define __VA_FOR_EACH_20(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))

#define __VA_FOR_EACH_21(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))

#define __VA_FOR_EACH_22(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))

#define __VA_FOR_EACH_23(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))

#define __VA_FOR_EACH_24(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))

#define __VA_FOR_EACH_25(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))

#define __VA_FOR_EACH_26(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))

#define __VA_FOR_EACH_27(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))

#define __VA_FOR_EACH_28(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))

#define __VA_FOR_EACH_29(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))

#define __VA_FOR_EACH_30(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))

#define __VA_FOR_EACH_31(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))

#define __VA_FOR_EACH_32(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))

#define __VA_FOR_EACH_33(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))

#define __VA_FOR_EACH_34(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))

#define __VA_FOR_EACH_35(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))

#define __VA_FOR_EACH_36(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))

#define __VA_FOR_EACH_37(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))

#define __VA_FOR_EACH_38(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))

#define __VA_FOR_EACH_39(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))

#define __VA_FOR_EACH_40(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))

#define __VA_FOR_EACH_41(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))

#define __VA_FOR_EACH_42(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))

#define __VA_FOR_EACH_43(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))\
MACRO(__VA_ARG_42(__VA_ARGS__))

#define __VA_FOR_EACH_44(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))\
MACRO(__VA_ARG_42(__VA_ARGS__))\
MACRO(__VA_ARG_43(__VA_ARGS__))

#define __VA_FOR_EACH_45(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))\
MACRO(__VA_ARG_42(__VA_ARGS__))\
MACRO(__VA_ARG_43(__VA_ARGS__))\
MACRO(__VA_ARG_44(__VA_ARGS__))

#define __VA_FOR_EACH_46(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))\
MACRO(__VA_ARG_42(__VA_ARGS__))\
MACRO(__VA_ARG_43(__VA_ARGS__))\
MACRO(__VA_ARG_44(__VA_ARGS__))\
MACRO(__VA_ARG_45(__VA_ARGS__))

#define __VA_FOR_EACH_47(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))\
MACRO(__VA_ARG_42(__VA_ARGS__))\
MACRO(__VA_ARG_43(__VA_ARGS__))\
MACRO(__VA_ARG_44(__VA_ARGS__))\
MACRO(__VA_ARG_45(__VA_ARGS__))\
MACRO(__VA_ARG_46(__VA_ARGS__))

#define __VA_FOR_EACH_48(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))\
MACRO(__VA_ARG_42(__VA_ARGS__))\
MACRO(__VA_ARG_43(__VA_ARGS__))\
MACRO(__VA_ARG_44(__VA_ARGS__))\
MACRO(__VA_ARG_45(__VA_ARGS__))\
MACRO(__VA_ARG_46(__VA_ARGS__))\
MACRO(__VA_ARG_47(__VA_ARGS__))

#define __VA_FOR_EACH_49(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))\
MACRO(__VA_ARG_42(__VA_ARGS__))\
MACRO(__VA_ARG_43(__VA_ARGS__))\
MACRO(__VA_ARG_44(__VA_ARGS__))\
MACRO(__VA_ARG_45(__VA_ARGS__))\
MACRO(__VA_ARG_46(__VA_ARGS__))\
MACRO(__VA_ARG_47(__VA_ARGS__))\
MACRO(__VA_ARG_48(__VA_ARGS__))

#define __VA_FOR_EACH_50(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))\
MACRO(__VA_ARG_42(__VA_ARGS__))\
MACRO(__VA_ARG_43(__VA_ARGS__))\
MACRO(__VA_ARG_44(__VA_ARGS__))\
MACRO(__VA_ARG_45(__VA_ARGS__))\
MACRO(__VA_ARG_46(__VA_ARGS__))\
MACRO(__VA_ARG_47(__VA_ARGS__))\
MACRO(__VA_ARG_48(__VA_ARGS__))\
MACRO(__VA_ARG_49(__VA_ARGS__))

#define __VA_FOR_EACH_51(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))\
MACRO(__VA_ARG_42(__VA_ARGS__))\
MACRO(__VA_ARG_43(__VA_ARGS__))\
MACRO(__VA_ARG_44(__VA_ARGS__))\
MACRO(__VA_ARG_45(__VA_ARGS__))\
MACRO(__VA_ARG_46(__VA_ARGS__))\
MACRO(__VA_ARG_47(__VA_ARGS__))\
MACRO(__VA_ARG_48(__VA_ARGS__))\
MACRO(__VA_ARG_49(__VA_ARGS__))\
MACRO(__VA_ARG_50(__VA_ARGS__))

#define __VA_FOR_EACH_52(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))\
MACRO(__VA_ARG_42(__VA_ARGS__))\
MACRO(__VA_ARG_43(__VA_ARGS__))\
MACRO(__VA_ARG_44(__VA_ARGS__))\
MACRO(__VA_ARG_45(__VA_ARGS__))\
MACRO(__VA_ARG_46(__VA_ARGS__))\
MACRO(__VA_ARG_47(__VA_ARGS__))\
MACRO(__VA_ARG_48(__VA_ARGS__))\
MACRO(__VA_ARG_49(__VA_ARGS__))\
MACRO(__VA_ARG_50(__VA_ARGS__))\
MACRO(__VA_ARG_51(__VA_ARGS__))

#define __VA_FOR_EACH_53(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))\
MACRO(__VA_ARG_42(__VA_ARGS__))\
MACRO(__VA_ARG_43(__VA_ARGS__))\
MACRO(__VA_ARG_44(__VA_ARGS__))\
MACRO(__VA_ARG_45(__VA_ARGS__))\
MACRO(__VA_ARG_46(__VA_ARGS__))\
MACRO(__VA_ARG_47(__VA_ARGS__))\
MACRO(__VA_ARG_48(__VA_ARGS__))\
MACRO(__VA_ARG_49(__VA_ARGS__))\
MACRO(__VA_ARG_50(__VA_ARGS__))\
MACRO(__VA_ARG_51(__VA_ARGS__))\
MACRO(__VA_ARG_52(__VA_ARGS__))

#define __VA_FOR_EACH_54(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))\
MACRO(__VA_ARG_42(__VA_ARGS__))\
MACRO(__VA_ARG_43(__VA_ARGS__))\
MACRO(__VA_ARG_44(__VA_ARGS__))\
MACRO(__VA_ARG_45(__VA_ARGS__))\
MACRO(__VA_ARG_46(__VA_ARGS__))\
MACRO(__VA_ARG_47(__VA_ARGS__))\
MACRO(__VA_ARG_48(__VA_ARGS__))\
MACRO(__VA_ARG_49(__VA_ARGS__))\
MACRO(__VA_ARG_50(__VA_ARGS__))\
MACRO(__VA_ARG_51(__VA_ARGS__))\
MACRO(__VA_ARG_52(__VA_ARGS__))\
MACRO(__VA_ARG_53(__VA_ARGS__))

#define __VA_FOR_EACH_55(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))\
MACRO(__VA_ARG_42(__VA_ARGS__))\
MACRO(__VA_ARG_43(__VA_ARGS__))\
MACRO(__VA_ARG_44(__VA_ARGS__))\
MACRO(__VA_ARG_45(__VA_ARGS__))\
MACRO(__VA_ARG_46(__VA_ARGS__))\
MACRO(__VA_ARG_47(__VA_ARGS__))\
MACRO(__VA_ARG_48(__VA_ARGS__))\
MACRO(__VA_ARG_49(__VA_ARGS__))\
MACRO(__VA_ARG_50(__VA_ARGS__))\
MACRO(__VA_ARG_51(__VA_ARGS__))\
MACRO(__VA_ARG_52(__VA_ARGS__))\
MACRO(__VA_ARG_53(__VA_ARGS__))\
MACRO(__VA_ARG_54(__VA_ARGS__))

#define __VA_FOR_EACH_56(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))\
MACRO(__VA_ARG_42(__VA_ARGS__))\
MACRO(__VA_ARG_43(__VA_ARGS__))\
MACRO(__VA_ARG_44(__VA_ARGS__))\
MACRO(__VA_ARG_45(__VA_ARGS__))\
MACRO(__VA_ARG_46(__VA_ARGS__))\
MACRO(__VA_ARG_47(__VA_ARGS__))\
MACRO(__VA_ARG_48(__VA_ARGS__))\
MACRO(__VA_ARG_49(__VA_ARGS__))\
MACRO(__VA_ARG_50(__VA_ARGS__))\
MACRO(__VA_ARG_51(__VA_ARGS__))\
MACRO(__VA_ARG_52(__VA_ARGS__))\
MACRO(__VA_ARG_53(__VA_ARGS__))\
MACRO(__VA_ARG_54(__VA_ARGS__))\
MACRO(__VA_ARG_55(__VA_ARGS__))

#define __VA_FOR_EACH_57(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))\
MACRO(__VA_ARG_42(__VA_ARGS__))\
MACRO(__VA_ARG_43(__VA_ARGS__))\
MACRO(__VA_ARG_44(__VA_ARGS__))\
MACRO(__VA_ARG_45(__VA_ARGS__))\
MACRO(__VA_ARG_46(__VA_ARGS__))\
MACRO(__VA_ARG_47(__VA_ARGS__))\
MACRO(__VA_ARG_48(__VA_ARGS__))\
MACRO(__VA_ARG_49(__VA_ARGS__))\
MACRO(__VA_ARG_50(__VA_ARGS__))\
MACRO(__VA_ARG_51(__VA_ARGS__))\
MACRO(__VA_ARG_52(__VA_ARGS__))\
MACRO(__VA_ARG_53(__VA_ARGS__))\
MACRO(__VA_ARG_54(__VA_ARGS__))\
MACRO(__VA_ARG_55(__VA_ARGS__))\
MACRO(__VA_ARG_56(__VA_ARGS__))

#define __VA_FOR_EACH_58(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))\
MACRO(__VA_ARG_42(__VA_ARGS__))\
MACRO(__VA_ARG_43(__VA_ARGS__))\
MACRO(__VA_ARG_44(__VA_ARGS__))\
MACRO(__VA_ARG_45(__VA_ARGS__))\
MACRO(__VA_ARG_46(__VA_ARGS__))\
MACRO(__VA_ARG_47(__VA_ARGS__))\
MACRO(__VA_ARG_48(__VA_ARGS__))\
MACRO(__VA_ARG_49(__VA_ARGS__))\
MACRO(__VA_ARG_50(__VA_ARGS__))\
MACRO(__VA_ARG_51(__VA_ARGS__))\
MACRO(__VA_ARG_52(__VA_ARGS__))\
MACRO(__VA_ARG_53(__VA_ARGS__))\
MACRO(__VA_ARG_54(__VA_ARGS__))\
MACRO(__VA_ARG_55(__VA_ARGS__))\
MACRO(__VA_ARG_56(__VA_ARGS__))\
MACRO(__VA_ARG_57(__VA_ARGS__))

#define __VA_FOR_EACH_59(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))\
MACRO(__VA_ARG_42(__VA_ARGS__))\
MACRO(__VA_ARG_43(__VA_ARGS__))\
MACRO(__VA_ARG_44(__VA_ARGS__))\
MACRO(__VA_ARG_45(__VA_ARGS__))\
MACRO(__VA_ARG_46(__VA_ARGS__))\
MACRO(__VA_ARG_47(__VA_ARGS__))\
MACRO(__VA_ARG_48(__VA_ARGS__))\
MACRO(__VA_ARG_49(__VA_ARGS__))\
MACRO(__VA_ARG_50(__VA_ARGS__))\
MACRO(__VA_ARG_51(__VA_ARGS__))\
MACRO(__VA_ARG_52(__VA_ARGS__))\
MACRO(__VA_ARG_53(__VA_ARGS__))\
MACRO(__VA_ARG_54(__VA_ARGS__))\
MACRO(__VA_ARG_55(__VA_ARGS__))\
MACRO(__VA_ARG_56(__VA_ARGS__))\
MACRO(__VA_ARG_57(__VA_ARGS__))\
MACRO(__VA_ARG_58(__VA_ARGS__))

#define __VA_FOR_EACH_60(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))\
MACRO(__VA_ARG_42(__VA_ARGS__))\
MACRO(__VA_ARG_43(__VA_ARGS__))\
MACRO(__VA_ARG_44(__VA_ARGS__))\
MACRO(__VA_ARG_45(__VA_ARGS__))\
MACRO(__VA_ARG_46(__VA_ARGS__))\
MACRO(__VA_ARG_47(__VA_ARGS__))\
MACRO(__VA_ARG_48(__VA_ARGS__))\
MACRO(__VA_ARG_49(__VA_ARGS__))\
MACRO(__VA_ARG_50(__VA_ARGS__))\
MACRO(__VA_ARG_51(__VA_ARGS__))\
MACRO(__VA_ARG_52(__VA_ARGS__))\
MACRO(__VA_ARG_53(__VA_ARGS__))\
MACRO(__VA_ARG_54(__VA_ARGS__))\
MACRO(__VA_ARG_55(__VA_ARGS__))\
MACRO(__VA_ARG_56(__VA_ARGS__))\
MACRO(__VA_ARG_57(__VA_ARGS__))\
MACRO(__VA_ARG_58(__VA_ARGS__))\
MACRO(__VA_ARG_59(__VA_ARGS__))

#define __VA_FOR_EACH_61(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))\
MACRO(__VA_ARG_42(__VA_ARGS__))\
MACRO(__VA_ARG_43(__VA_ARGS__))\
MACRO(__VA_ARG_44(__VA_ARGS__))\
MACRO(__VA_ARG_45(__VA_ARGS__))\
MACRO(__VA_ARG_46(__VA_ARGS__))\
MACRO(__VA_ARG_47(__VA_ARGS__))\
MACRO(__VA_ARG_48(__VA_ARGS__))\
MACRO(__VA_ARG_49(__VA_ARGS__))\
MACRO(__VA_ARG_50(__VA_ARGS__))\
MACRO(__VA_ARG_51(__VA_ARGS__))\
MACRO(__VA_ARG_52(__VA_ARGS__))\
MACRO(__VA_ARG_53(__VA_ARGS__))\
MACRO(__VA_ARG_54(__VA_ARGS__))\
MACRO(__VA_ARG_55(__VA_ARGS__))\
MACRO(__VA_ARG_56(__VA_ARGS__))\
MACRO(__VA_ARG_57(__VA_ARGS__))\
MACRO(__VA_ARG_58(__VA_ARGS__))\
MACRO(__VA_ARG_59(__VA_ARGS__))\
MACRO(__VA_ARG_60(__VA_ARGS__))

#define __VA_FOR_EACH_62(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))\
MACRO(__VA_ARG_42(__VA_ARGS__))\
MACRO(__VA_ARG_43(__VA_ARGS__))\
MACRO(__VA_ARG_44(__VA_ARGS__))\
MACRO(__VA_ARG_45(__VA_ARGS__))\
MACRO(__VA_ARG_46(__VA_ARGS__))\
MACRO(__VA_ARG_47(__VA_ARGS__))\
MACRO(__VA_ARG_48(__VA_ARGS__))\
MACRO(__VA_ARG_49(__VA_ARGS__))\
MACRO(__VA_ARG_50(__VA_ARGS__))\
MACRO(__VA_ARG_51(__VA_ARGS__))\
MACRO(__VA_ARG_52(__VA_ARGS__))\
MACRO(__VA_ARG_53(__VA_ARGS__))\
MACRO(__VA_ARG_54(__VA_ARGS__))\
MACRO(__VA_ARG_55(__VA_ARGS__))\
MACRO(__VA_ARG_56(__VA_ARGS__))\
MACRO(__VA_ARG_57(__VA_ARGS__))\
MACRO(__VA_ARG_58(__VA_ARGS__))\
MACRO(__VA_ARG_59(__VA_ARGS__))\
MACRO(__VA_ARG_60(__VA_ARGS__))\
MACRO(__VA_ARG_61(__VA_ARGS__))

#define __VA_FOR_EACH_63(MACRO, ...)\
MACRO(__VA_ARG_0(__VA_ARGS__))\
MACRO(__VA_ARG_1(__VA_ARGS__))\
MACRO(__VA_ARG_2(__VA_ARGS__))\
MACRO(__VA_ARG_3(__VA_ARGS__))\
MACRO(__VA_ARG_4(__VA_ARGS__))\
MACRO(__VA_ARG_5(__VA_ARGS__))\
MACRO(__VA_ARG_6(__VA_ARGS__))\
MACRO(__VA_ARG_7(__VA_ARGS__))\
MACRO(__VA_ARG_8(__VA_ARGS__))\
MACRO(__VA_ARG_9(__VA_ARGS__))\
MACRO(__VA_ARG_10(__VA_ARGS__))\
MACRO(__VA_ARG_11(__VA_ARGS__))\
MACRO(__VA_ARG_12(__VA_ARGS__))\
MACRO(__VA_ARG_13(__VA_ARGS__))\
MACRO(__VA_ARG_14(__VA_ARGS__))\
MACRO(__VA_ARG_15(__VA_ARGS__))\
MACRO(__VA_ARG_16(__VA_ARGS__))\
MACRO(__VA_ARG_17(__VA_ARGS__))\
MACRO(__VA_ARG_18(__VA_ARGS__))\
MACRO(__VA_ARG_19(__VA_ARGS__))\
MACRO(__VA_ARG_20(__VA_ARGS__))\
MACRO(__VA_ARG_21(__VA_ARGS__))\
MACRO(__VA_ARG_22(__VA_ARGS__))\
MACRO(__VA_ARG_23(__VA_ARGS__))\
MACRO(__VA_ARG_24(__VA_ARGS__))\
MACRO(__VA_ARG_25(__VA_ARGS__))\
MACRO(__VA_ARG_26(__VA_ARGS__))\
MACRO(__VA_ARG_27(__VA_ARGS__))\
MACRO(__VA_ARG_28(__VA_ARGS__))\
MACRO(__VA_ARG_29(__VA_ARGS__))\
MACRO(__VA_ARG_30(__VA_ARGS__))\
MACRO(__VA_ARG_31(__VA_ARGS__))\
MACRO(__VA_ARG_32(__VA_ARGS__))\
MACRO(__VA_ARG_33(__VA_ARGS__))\
MACRO(__VA_ARG_34(__VA_ARGS__))\
MACRO(__VA_ARG_35(__VA_ARGS__))\
MACRO(__VA_ARG_36(__VA_ARGS__))\
MACRO(__VA_ARG_37(__VA_ARGS__))\
MACRO(__VA_ARG_38(__VA_ARGS__))\
MACRO(__VA_ARG_39(__VA_ARGS__))\
MACRO(__VA_ARG_40(__VA_ARGS__))\
MACRO(__VA_ARG_41(__VA_ARGS__))\
MACRO(__VA_ARG_42(__VA_ARGS__))\
MACRO(__VA_ARG_43(__VA_ARGS__))\
MACRO(__VA_ARG_44(__VA_ARGS__))\
MACRO(__VA_ARG_45(__VA_ARGS__))\
MACRO(__VA_ARG_46(__VA_ARGS__))\
MACRO(__VA_ARG_47(__VA_ARGS__))\
MACRO(__VA_ARG_48(__VA_ARGS__))\
MACRO(__VA_ARG_49(__VA_ARGS__))\
MACRO(__VA_ARG_50(__VA_ARGS__))\
MACRO(__VA_ARG_51(__VA_ARGS__))\
MACRO(__VA_ARG_52(__VA_ARGS__))\
MACRO(__VA_ARG_53(__VA_ARGS__))\
MACRO(__VA_ARG_54(__VA_ARGS__))\
MACRO(__VA_ARG_55(__VA_ARGS__))\
MACRO(__VA_ARG_56(__VA_ARGS__))\
MACRO(__VA_ARG_57(__VA_ARGS__))\
MACRO(__VA_ARG_58(__VA_ARGS__))\
MACRO(__VA_ARG_59(__VA_ARGS__))\
MACRO(__VA_ARG_60(__VA_ARGS__))\
MACRO(__VA_ARG_61(__VA_ARGS__))\
MACRO(__VA_ARG_62(__VA_ARGS__))