$qt_path = "C:/Qt5"
$build_folder = $qt_path + "/qtbuild"
& "$qt_path/configure.bat" -opensource `
-confirm-license `
-platform win32-msvc `
-mp `
-debug-and-release `
-static `
-static-runtime `
-prefix "C:/Qt5/static-msvc/" `
-D "JAS_DLL=0" `
-strip `
-optimize-size `
-silent `
-no-sql-odbc `
-no-compile-examples `
-nomake tests `
-nomake examples `
-no-opengl `
-no-feature-concurrent `
-no-feature-xml `
-no-feature-testlib `
-no-zlib `
-no-gif `
-no-ico `
-no-freetype `
-no-libjpeg `
-no-libpng `
-no-xcb `
-no-pcre `
-no-harfbuzz `
-skip qt3d `
-skip qtactiveqt `
-skip qtandroidextras `
-skip qtcharts `
-skip qtconnectivity `
-skip qtdatavis3d `
-skip qtdeclarative `
-skip qtdoc `
-skip qtgamepad `
-skip qtgraphicaleffects `
-skip qtimageformats `
-skip qtlocation `
-skip qtlottie `
-skip qtmacextras `
-skip qtmultimedia `
-skip qtnetworkauth `
-skip qtpurchasing `
-skip qtquick3d `
-skip qtquickcontrols `
-skip qtquickcontrols2 `
-skip qtquicktimeline `
-skip qtremoteobjects `
-skip qtscript `
-skip qtscxml `
-skip qtsensors `
-skip qtserialbus `
-skip qtserialport `
-skip qtspeech `
-skip qtsvg `
-skip qttools `
-skip qttranslations `
-skip qtvirtualkeyboard `
-skip qtwayland `
-skip qtwebchannel `
-skip qtwebengine `
-skip qtwebsockets `
-skip qtwebview `
-skip qtwinextras `
-skip qtx11extras `
-skip qtxmlpatterns